# Site settings
title: 莱锦德锐
SEOTitle: 莱锦德锐 | 记录悲惨生活
header-img: img/home-bg-milky-way.jpg
email: hi@liukai.lk
description: "记录悲惨生活"
keyword: ""
url: "https://igeeker.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/igeeker/igeeker.github.io.git" # you code repository

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
email_address: hi@liukai.lk
website: true
jianshu_username:   xfyqAx
weibo_username:     igeeker
zhihu_username:   igeeker
about_me_username: igeeker
github_username:   igeeker
twitter_username:   igeeker
facebook_username:  igeeker
linkedin_username:  igeeker



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: #igeeker

# Netease settings
netease_comment: false

# Valine settings (igeeker)
valine_appId: rJsjuTMoAslQV5G04cI9g3zC-gzGzoHsz
valine_appKey: nAy4XrI8I488Vn349MAQD673


# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-121324923-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto  # 默认的是 auto, 如果自定义了域名，需要填上域名



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一个脱离高级趣味的人"
sidebar-avatar: /img/avatar-liukai.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 2              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true



# Friends
# friends: [
#    {
#        title: "Hux Blog",#
#        href: "http://huangxuan.me"
#    } # ,{
#        title: "Mike Lyou Blog",
#        href: "https://blog.mikelyou.com"
#    },{
#        title: "Bar",
#        href: "#"
#    },{
#        title: "Example Friends",
#        href: "#"
#    },{
#        title: "It helps SEO",
#        href: "#"
#    }
# ]


# blog configuration

excerpt_separator:  '<!-- more -->'
